context:
  version: "20.1.8"

package:
  name: llvm-filecheck
  version: ${{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ version }}/llvm-project-${{ version }}.src.tar.xz
  sha256: 6898f963c8e938981e6c4a302e83ec5beb4630147c7311183cf61069af16333d

build:
  number: 0
  script:
    - if: unix
      then: |
        cmake -S llvm -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=${PREFIX} \
          -DLLVM_TARGETS_TO_BUILD=host \
          -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_INCLUDE_EXAMPLES=OFF \
          -DLLVM_INCLUDE_BENCHMARKS=OFF \
          -DLLVM_ENABLE_ZLIB=OFF \
          -DLLVM_ENABLE_ZSTD=OFF \
          -DLLVM_ENABLE_ASSERTIONS=OFF
        cmake --build build --target FileCheck --config Release
        install -d "${PREFIX}/bin"
        if [ -f "build/bin/FileCheck" ]; then cp build/bin/FileCheck "${PREFIX}/bin/"; fi
    - if: win
      then: |
        if "%CC%"=="" (echo CC not set & exit /b 1)
        if /I "%CC%"=="cl.exe" (
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSINSTALLDIR=%%i"
          if not defined VSINSTALLDIR (echo Visual Studio not found & exit /b 1)
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvars64.bat"
        )
        cmake -S llvm -B build -G Ninja ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
          -DLLVM_TARGETS_TO_BUILD=host ^
          -DLLVM_INCLUDE_TESTS=OFF ^
          -DLLVM_INCLUDE_EXAMPLES=OFF ^
          -DLLVM_INCLUDE_BENCHMARKS=OFF ^
          -DLLVM_ENABLE_ZLIB=OFF ^
          -DLLVM_ENABLE_ZSTD=OFF ^
          -DLLVM_ENABLE_ASSERTIONS=OFF
        cmake --build build --target FileCheck --config Release
        if not exist "%LIBRARY_PREFIX%\bin" mkdir "%LIBRARY_PREFIX%\bin"
        set "FC_SRC="
        if exist "build\bin\FileCheck.exe" set "FC_SRC=build\bin\FileCheck.exe"
        if exist "build\bin\Release\FileCheck.exe" set "FC_SRC=build\bin\Release\FileCheck.exe"
        if exist "build\Release\bin\FileCheck.exe" set "FC_SRC=build\Release\bin\FileCheck.exe"
        if "%FC_SRC%"=="" (echo FileCheck.exe not found & exit /b 1)
        copy /Y "%FC_SRC%" "%LIBRARY_PREFIX%\bin\FileCheck.exe"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - if: linux
      then: sysroot_linux-64 ==2.17
    - if: osx
      then:
        - lld ==20.1.8
        - llvm-tools ==20.1.8
        - compiler-rt ==20.1.8
  host:
    - if: osx
      then: libcxx ${{ c_stdlib_version }}
  run:
    - if: osx
      then: libcxx ${{ c_stdlib_version }}

tests:
  - if: unix
    then:
      script: |
        FileCheck --version
        printf "hello\n" > input.txt
        printf "CHECK: hello\n" > check.txt
        FileCheck check.txt < input.txt
  - if: win
    then:
      script: |
        FileCheck --version
        echo hello> input.txt
        echo CHECK: hello> check.txt
        type input.txt | FileCheck check.txt

about:
  homepage: https://llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  summary: LLVM FileCheck utility
  repository: https://github.com/llvm/llvm-project
